---
- import_tasks: download-image.yml

- import_tasks: import-snippets.yml

- import_tasks: create-vm.yml

- name: Configure VM
  block:
    - import_tasks: configure-vm.yml
  rescue:
    - import_tasks: destroy-vm.yml
  when: __vm_create__.changed
