---
name: Validate Role

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  molecule:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        role:
          - anacron

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies.
        run: pip3 install yamllint ansible-lint ansible "molecule[lint,docker]" "molecule-plugins[docker]"

      - name: Install Galaxy dependencies.
        run: ansible-galaxy collection install community.docker

      - name: Run molecule
        run: cd roles/${{ matrix.role }} && molecule test
