---
name: Validate Role

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  molecule:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        role:
          - anacron
          - ansible
          - docker
          - downloader
          - opnsense-dashboard
          - opnsense-dhcp
          - opnsense-firewall_rules
          - opnsense-gateway
          - opnsense-general-settings
          - opnsense-interfaces
          - opnsense-plugins
          - opnsense-ssh
          - opnsense-theme
          - opnsense-unbound
          - proxmox-cloudbuntu
          - proxmox-dark-theme
          - proxmox-driver-blacklist
          - proxmox-iommu
          - proxmox-nested-virt
          - proxmox-no-subscription
          - proxmox-pci-passthrough
          - proxmox-vfio
          - proxmox-vgpu
          - rust

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies.
        run: pip3 install -r requirements.txt

      - name: Run molecule
        run: cd roles/${{ matrix.role }} && molecule test
